#
#  Copyright (C) 2015 - Garvan Institute of Medical Research
#
#  Ted Wong, Bioinformatic Software Engineer at Garvan Institute
#

#
# Read the genes.fpkm_tracking file generated by Cufflink.
#

cufflink.genes <- function(f1, f2, f3, f4, f5, f6)
{
    d1 <- read.csv(f1, sep='\t')
    d2 <- read.csv(f2, sep='\t')
    d3 <- read.csv(f3, sep='\t')
    d4 <- read.csv(f4, sep='\t')
    d5 <- read.csv(f5, sep='\t')
    d6 <- read.csv(f6, sep='\t')
    
    d1 <- data.frame(row.names = d1$tracking_id, counts = d1$FPKM)
    d2 <- data.frame(row.names = d2$tracking_id, counts = d2$FPKM)
    d3 <- data.frame(row.names = d3$tracking_id, counts = d3$FPKM)
    d4 <- data.frame(row.names = d4$tracking_id, counts = d4$FPKM)
    d5 <- data.frame(row.names = d5$tracking_id, counts = d5$FPKM)
    d6 <- data.frame(row.names = d6$tracking_id, counts = d6$FPKM)    
    
    d <- data.frame(row.names = row.names(d1),
                    A1 = rep('NA', nrow(d1)),
                    A2 = rep('NA', nrow(d2)),
                    A3 = rep('NA', nrow(d3)),
                    B1 = rep('NA', nrow(d4)),
                    B2 = rep('NA', nrow(d5)),
                    B3 = rep('NA', nrow(d6)))
    d$A1 <- d1$counts
    d$A2 <- d2$counts
    d$A3 <- d3$counts
    d$B1 <- d4$counts
    d$B2 <- d5$counts
    d$B3 <- d6$counts
    
    d <- d[with(d, order(row.names(d))),]
    d
}

#
# Read the isoforms.fpkm_tracking file generated by Cufflink.
#

cufflink.isoforms <- function(f1, f2, f3, f4, f5, f6)
{
    d1 <- read.csv(f1, sep='\t')
    d2 <- read.csv(f2, sep='\t')
    d3 <- read.csv(f3, sep='\t')
    d4 <- read.csv(f4, sep='\t')
    d5 <- read.csv(f5, sep='\t')
    d6 <- read.csv(f6, sep='\t')

    d1 <- data.frame(row.names = d1$tracking_id, counts = d1$FPKM)
    d2 <- data.frame(row.names = d2$tracking_id, counts = d2$FPKM)
    d3 <- data.frame(row.names = d3$tracking_id, counts = d3$FPKM)
    d4 <- data.frame(row.names = d4$tracking_id, counts = d4$FPKM)
    d5 <- data.frame(row.names = d5$tracking_id, counts = d5$FPKM)
    d6 <- data.frame(row.names = d6$tracking_id, counts = d6$FPKM)    

    d <- data.frame(row.names = row.names(d1),
                           A1 = rep('NA', nrow(d1)),
                           A2 = rep('NA', nrow(d2)),
                           A3 = rep('NA', nrow(d3)),
                           B1 = rep('NA', nrow(d4)),
                           B2 = rep('NA', nrow(d5)),
                           B3 = rep('NA', nrow(d6)))
    d$A1 <- d1$counts
    d$A2 <- d2$counts
    d$A3 <- d3$counts
    d$B1 <- d4$counts
    d$B2 <- d5$counts
    d$B3 <- d6$counts

    d <- d[with(d, order(row.names(d))),]
    d
}
