#
# Anaquin - Sequin statistical analysis. Version %1%.
#
# This R script was generated by Anaquin at %2%.
#
#    %3%
#

d <- data.frame(x=c(%4%), x=c(%5%), ids=c(%6%))

# Pearson's correlation
#p <- cor(x, y)

# Fit a simple linear regression model
#m <- lm(y~x)

# Prints a summary statistics of the model
#summary(m)

qplot(x, y, xlab='Log2 spike amount (attomoles/ul)', ylab='Log2 measured coverage (%5%)') + 
        geom_smooth(method='lm', formula=y~x)

# Legend for correlation
#legend("top", legend=c(paste('r:', round(cor(x,y), 4))), bty = "n")

# Legend for R2
#legend("topright", legend=c(paste('R2:', round(summary(m)$r.squared, 4))), bty = "n")