\documentclass[10pt,a4paper]{article}

\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{fancyhdr}
\usepackage{geometry}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{siunitx}
\usepackage{amsfonts}
\setlength{\headheight}{15.2pt}
\pagestyle{fancy}
\begin{document}
%\tableofcontents{}

<<setup, cache=FALSE, echo=FALSE, message=FALSE, warning=FALSE>>=
library(xtable)
library(stargazer)

source("VarMutationReport.R")
@

\newcommand{\HRule}{\rule{\linewidth}{0.5mm}}

\fancyhf{}
\lhead{Sequins Report}
\rhead{Page \thepage\ of \pageref{LastPage}}

\let\endtitlepage\relax
\begin{titlepage}
\begin{flushleft}
\LARGE{Sequins Report}
\HRule
\end{flushleft}
\end{titlepage}

\LARGE{Report files}

\section{Reference Files}

<<results='asis', echo=FALSE>>=
stargazer(refs, summary=FALSE, rownames=FALSE, title='Reference files for this report')
@

\section{Input Files}

<<results='asis', echo=FALSE>>=
stargazer(inputs, summary=FALSE, rownames=FALSE, title='Input files for this report')
@

\pagebreak

\LARGE{Germline sequins}

\section{Summary statistics}

<<results='asis', echo=FALSE>>=
stargazer(germs, summary=FALSE, rownames=FALSE, title='Germline sequin variants')
@

\section{Germline Metric}

<<results='asis', echo=FALSE>>=
stargazer(germs.m, summary=FALSE, title='Germline sequin metrics')
@

\end{document}
